#' Retrieves the extent of an object's bonding box
#' 
#' @export
#' @param x numeric, SpatVector, SpatRaster, sf or stars object
#' @return numeric vector of bounding box in [xmin, xmax, ymin, ymax] order
as_bb <- function(x){
  
  if (any(inherits(x, c("sfc", "sf", "stars")))){
    x <- (sf::st_bbox(x) |> as.vector())[c(1,3,2,4)]
  } else if (any(inherits(x, c("SpatVector", "SpatRaster")))){
    x <- terra::ext(x) |> unname()
  }
  x
}

#' Resize a stars raster by a multiplier
#' 
#' A warning may be generated by `GDAL` about missing values.  THis warning may be 
#' ignored in most cases.
#' 
#' @export
#' @param x stars object
#' @param m num, a one or two element multiplier to modify the size of cells.
#'   m < 1 increases the number of cells, and m > 1 decreases the number of cells
#' @param ... other arguments for [stars::st_warp]
#' @return a resized stars object
resize = function(x = read_etopo(), m = 2, ...){
  d = stars::st_dimensions(x)
  d = sapply(names(d), function(nm) d[[nm]]$delta)
  r = stars::st_warp(x, 
                     cellsize = d[1:2] * m, 
                     use_gdal = TRUE, 
                     no_data_value = NA_real_,
                     ...)
  names(r) <- names(x)
  r
}
